# Generated by Django 5.2.1 on 2025-06-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='部員の学年を入力してください（例：1〜3）', null=True, verbose_name='学年'),
        ),
    ]
