@startuml ER
skinparam defaultFontName "Noto Sans CJK JP"
entity "ユーザーマスター" as User {
  +ユーザーID <<PK>>
  +ログイン名 <<UNIQUE>>
  +メールアドレス
  +パスワード
  + 姓
  + 名
  +ロール <<マネージャー/部員/コーチ/監督>>
}

entity "測定記録" as Measurement {
  +測定記録結果ID <<PK>>
  +ユーザーID <<FK>> -- 測定対象者（部員）
  +作成者ID <<FK>> -- 測定記録を登録したマネージャー
  +測定日
  +50m走（秒）
  +ベースランニング（秒）
  +遠投（m）
  +ストレート球速（km/h）
  +打球速度（km/h）
  +スイング速度（km/h）
  +ベンチプレス（kg）
  +スクワット（kg）
  +ステータス <<承認待ち/部員承認済み/コーチ承認済み/否認>>
  +再作成日時
}

entity "承認履歴" as MeasurementApproval {
  +承認履歴ID <<PK>>
  +ユーザーID <<FK>> -- 測定対象者（部員）
  +作成者ID <<FK>> -- 測定記録を登録したマネージャー
  +測定日
  +50m走（秒）
  +ベースランニング（秒）
  +遠投（m）
  +ストレート球速（km/h）
  +打球速度（km/h）
  +スイング速度（km/h）
  +ベンチプレス（kg）
  +スクワット（kg）
  +ステータス <<承認待ち/部員承認済み/コーチ承認済み/否認>>
  +再作成日時
}

User ||--o{ Measurement : 対象者（ユーザーID）
User ||--o{ Measurement : 作成者（ユーザーID）

@enduml
