# Generated by Django 5.2.1 on 2025-06-03 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0002_alter_measurement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'マネージャー'), ('player', '部員'), ('coach', 'コーチ'), ('director', '監督')], max_length=10)),
                ('step', models.CharField(choices=[('self', '部員による承認'), ('coach', 'コーチの最終承認')], max_length=10)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('approved', '承認'), ('rejected', '否認')], max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='measurements.measurement')),
            ],
            options={
                'verbose_name': '承認履歴',
                'verbose_name_plural': '承認履歴',
                'unique_together': {('measurement', 'approver', 'step')},
            },
        ),
    ]
