# Generated by Django 5.2.1 on 2025-06-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurementapproval',
            old_name='approved_at',
            new_name='created_at',
        ),
    ]
