# Generated by Django 5.2.1 on 2025-06-04 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_rename_approved_at_measurementapproval_created_at'),
        ('measurements', '0002_alter_measurement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurementapproval',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='measurementapproval',
            constraint=models.UniqueConstraint(fields=('measurement', 'approver', 'step'), name='unique_approval_once'),
        ),
    ]
