# Generated by Django 5.2.1 on 2025-06-09 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_alter_measurementapproval_unique_together_and_more'),
        ('measurements', '0005_alter_measurement_base_running_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
        migrations.AlterField(
            model_name='measurementapproval',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='measurementapproval',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='承認日時'),
        ),
        migrations.AlterField(
            model_name='measurementapproval',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='measurements.measurement', verbose_name='測定記録'),
        ),
        migrations.AlterField(
            model_name='measurementapproval',
            name='role',
            field=models.CharField(choices=[('manager', 'マネージャー'), ('player', '部員'), ('coach', 'コーチ'), ('director', '監督')], max_length=10, verbose_name='承認者の立場'),
        ),
        migrations.AlterField(
            model_name='measurementapproval',
            name='status',
            field=models.CharField(choices=[('approved', '承認'), ('rejected', '否認')], max_length=10, verbose_name='承認ステータス'),
        ),
        migrations.AlterField(
            model_name='measurementapproval',
            name='step',
            field=models.CharField(choices=[('self', '部員による承認'), ('coach', 'コーチの最終承認')], max_length=10, verbose_name='承認ステップ'),
        ),
    ]
