# Generated by Django 5.2.1 on 2025-06-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_alter_measurementapproval_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementapproval',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='コメント'),
            preserve_default=False,
        ),
    ]
