# Generated by Django 5.2.1 on 2025-06-20 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_alter_measurementapproval_comment'),
        ('measurements', '0006_alter_measurement_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='measurementapproval',
            name='unique_approval_once',
        ),
        migrations.RemoveField(
            model_name='measurementapproval',
            name='role',
        ),
        migrations.AddConstraint(
            model_name='measurementapproval',
            constraint=models.UniqueConstraint(fields=('measurement', 'step'), name='unique_step_approval_per_measurement'),
        ),
    ]
