# Generated by Django 5.2.1 on 2025-06-02 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sprint_50m', models.FloatField(help_text='50m走（秒）')),
                ('base_running', models.FloatField(help_text='ベースランニング（秒）')),
                ('long_throw', models.IntegerField(help_text='遠投（m）')),
                ('straight_ball_speed', models.IntegerField(help_text='ストレート球速（km/h）')),
                ('hit_ball_speed', models.IntegerField(help_text='打球速度（km/h）')),
                ('swing_speed', models.IntegerField(help_text='スイング速度（km/h）')),
                ('bench_press', models.IntegerField(help_text='ベンチプレス（kg）')),
                ('squat', models.IntegerField(help_text='スクワット（kg）')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('pending', '承認待ち'), ('player_approved', '部員承認済み'), ('coach_approved', 'コーチ承認済み')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_measurements', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'マネージャー'), ('player', '部員'), ('coach', 'コーチ'), ('director', '監督')], max_length=10)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('approved', '承認'), ('rejected', '否認')], max_length=10)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='measurements.measurement')),
            ],
        ),
    ]
