# Generated by Django 5.2.1 on 2025-06-03 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': '測定記録', 'verbose_name_plural': '測定記録'},
        ),
        migrations.AlterField(
            model_name='measurement',
            name='base_running',
            field=models.FloatField(help_text='ベースランニングのタイム（秒）を入力してください', verbose_name='ベースランニング（秒）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='bench_press',
            field=models.IntegerField(help_text='ベンチプレスの重量（kg）を入力してください', verbose_name='ベンチプレス（kg）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_measurements', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(help_text='日付を YYYY-MM-DD の形式で入力してください。例: 2025-01-01', verbose_name='測定日'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='hit_ball_speed',
            field=models.IntegerField(help_text='打球速度（km/h）を入力してください', verbose_name='打球速度（km/h）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='long_throw',
            field=models.IntegerField(help_text='遠投距離（メートル）を入力してください', verbose_name='遠投（m）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL, verbose_name='選手'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sprint_50m',
            field=models.FloatField(help_text='50m走のタイム（秒）を入力してください', verbose_name='50m走（秒）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='squat',
            field=models.IntegerField(help_text='スクワットの重量（kg）を入力してください', verbose_name='スクワット（kg）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('pending', '承認待ち'), ('player_approved', '部員承認済み'), ('coach_approved', 'コーチ承認済み')], default='draft', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='straight_ball_speed',
            field=models.IntegerField(help_text='ストレートの球速（km/h）を入力してください', verbose_name='ストレート球速（km/h）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='swing_speed',
            field=models.IntegerField(help_text='スイング速度（km/h）を入力してください', verbose_name='スイング速度（km/h）'),
        ),
        migrations.DeleteModel(
            name='MeasurementApproval',
        ),
    ]
