# Generated by Django 5.2.1 on 2025-06-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_measurement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='recreated_at',
            field=models.DateTimeField(blank=True, help_text='この記録が再作成された日時。再作成されていない場合は空。', null=True, verbose_name='再作成日時'),
        ),
    ]
