# Generated by Django 5.2.1 on 2025-06-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_measurement_recreated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='base_running',
            field=models.FloatField(help_text='ベースランニングのタイム（秒）を小数で入力してください。例: 13.5', verbose_name='ベースランニング（秒）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='bench_press',
            field=models.IntegerField(help_text='ベンチプレスの重量（kg）を整数で入力してください。例: 80', verbose_name='ベンチプレス（kg）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='hit_ball_speed',
            field=models.IntegerField(help_text='打球速度（km/h）を整数で入力してください。例: 125', verbose_name='打球速度（km/h）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='long_throw',
            field=models.IntegerField(help_text='遠投距離（メートル）を整数で入力してください。例: 85', verbose_name='遠投（m）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sprint_50m',
            field=models.FloatField(help_text='50m走のタイム（秒）を小数で入力してください。例: 6.25', verbose_name='50m走（秒）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='squat',
            field=models.IntegerField(help_text='スクワットの重量（kg）を整数で入力してください。例: 100', verbose_name='スクワット（kg）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='straight_ball_speed',
            field=models.IntegerField(help_text='ストレートの球速（km/h）を整数で入力してください。例: 130', verbose_name='ストレート球速（km/h）'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='swing_speed',
            field=models.IntegerField(help_text='スイング速度（km/h）を整数で入力してください。例: 111', verbose_name='スイング速度（km/h）'),
        ),
    ]
