# Generated by Django 5.2.1 on 2025-06-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_alter_measurement_base_running_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='status',
            field=models.CharField(choices=[('pending', '承認待ち'), ('player_approved', '部員承認済み'), ('coach_approved', 'コーチ承認済み'), ('rejected', '否認')], default='pending', max_length=20, verbose_name='ステータス'),
        ),
    ]
